#!/usr/bin/env bash
# Generate a Swarm compose overlay that passes .env.deploy application keys into
# the API service. Docker Stack does not support env_file; only variables listed
# under services.api.environment reach the container. Compose interpolation
# (${VAR}) is resolved from the shell when CI runs:
#   set -a && source .env.deploy && set +a && docker stack deploy ...
#
# Usage:
#   ci-generate-api-env-overlay.sh <path-to-.env.deploy> [output-yml]
#
# Keys excluded (deploy / Traefik / image build / stack-owned — not overlay):
#   DOMAIN, DOMAIN_API, TRAEFIK_*, API_IMAGE, WEB_IMAGE, VITE_API_URL
#   POSTGRES_* (owned by docker-stack.*.yml; overlay ${VAR:-} had no default)
#   JVSPATIAL_POSTGRES_DSN (composed at API boot from POSTGRES_* in main.py)
#   AGENTIVE_*, JVSPATIAL_LOG_DB_*, TESTING, PYTEST_CURRENT_TEST

set -euo pipefail

ENV_FILE="${1:?env file path required}"
OUT_FILE="${2:-docker-stack.api-env.overlay.yml}"

# Keys excluded (deploy / Traefik / image build / stack-owned — not overlay):
#   DOMAIN, DOMAIN_API, TRAEFIK_*, API_IMAGE, WEB_IMAGE, VITE_API_URL
#   POSTGRES_* (owned by docker-stack.*.yml — overlay ${VAR:-} had no default)
#   JVSPATIAL_POSTGRES_DSN (composed at API boot from POSTGRES_* in main.py)
#   AGENTIVE_*, JVSPATIAL_LOG_DB_*, TESTING, PYTEST_CURRENT_TEST
DENY_RE='^(DOMAIN|DOMAIN_API|TRAEFIK_.+|API_IMAGE|WEB_IMAGE|POSTGRES_IMAGE|VITE_API_URL|POSTGRES_.+|JVSPATIAL_POSTGRES_DSN|AGENTIVE_ENABLED|JVAGENT_UPDATE_MODE|JVSPATIAL_LOG_DB_TYPE|JVSPATIAL_LOG_DB_PATH|TESTING|PYTEST_CURRENT_TEST|WEB_CONCURRENCY|WORKERS)$'
# WEB_CONCURRENCY / WORKERS: denied because the overlay is passed AFTER the
# stack file (deploy.yml --compose-file order), so a value here would beat the
# stack's pin. >1 worker breaks chat invariants (per-process turn registry +
# websocket fan-out) with only a boot WARNING — ADR-004. Raising it must be a
# deliberate stack-file edit, not an env-file line nobody re-reads.

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ci-generate-api-env-overlay: file not found: $ENV_FILE" >&2
  exit 1
fi

tmp_keys="$(mktemp)"
trap 'rm -f "$tmp_keys"' EXIT

# Assignment lines only (KEY=...); ignore comments and blank lines.
grep -E '^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*=' "$ENV_FILE" | sed 's/^[[:space:]]*//' >"$tmp_keys" || true

{
  echo '# Generated by deploy/ci-generate-api-env-overlay.sh — do not edit on server.'
  echo '# Merged at deploy: docker stack deploy -c docker-stack.yml -c docker-stack.api-env.overlay.yml'
  echo 'version: "3.8"'
  echo 'services:'
  echo '  api:'
  echo '    environment:'
} >"$OUT_FILE"

count=0
while IFS= read -r line || [[ -n "$line" ]]; do
  key="${line%%=*}"
  key="${key%%[[:space:]]*}"
  [[ -z "$key" ]] && continue
  if [[ "$key" =~ $DENY_RE ]]; then
    continue
  fi
  # Shell-sourced at deploy time; empty if unset in .env.deploy.
  printf '      %s: ${%s:-}\n' "$key" "$key" >>"$OUT_FILE"
  count=$((count + 1))
done <"$tmp_keys"

if [[ "$count" -eq 0 ]]; then
  echo "ci-generate-api-env-overlay: warning: no API env keys emitted from $ENV_FILE" >&2
fi

echo "ci-generate-api-env-overlay: wrote $count keys to $OUT_FILE"
