/**
 * Phase 8 Plan 08-01 — extensible Settings nav scaffold.
 *
 * The const SECTIONS registry below is the SHARED REGISTRY across Phase 8.
 * 08-01 owns SettingsPage.tsx EXCLUSIVELY for the phase and pre-registers
 * ALL 11 sections (3 existing eager + 1 Policies eager + 7 lazy placeholders
 * filled by Plans 08-02..08-05). Downstream plans create / fill their
 * section file at the pre-agreed filepath — they DO NOT edit this file.
 *
 * Why React.lazy() for the downstream sections? Same-wave parallelism per
 * the planner's wave-assignment rule: no two same-wave plans modify the
 * same file. 08-01 lands the registry up-front so 08-02..08-05 can land
 * concurrently without touching SettingsPage.tsx.
 */
import React, { Suspense, useCallback, useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  AlertOctagon,
  Bell,
  BookOpen,
  Bot,
  Cable,
  Cpu,
  Info,
  Mic,
  Palette,
  ScrollText,
  Search,
  Settings as SettingsIcon,
  Share2,
  ShieldCheck,
  Sparkles,
  UserCircle,
  Wrench,
} from 'lucide-react';

import { useSettings } from '../features/settings/store';
import { AppearanceSection } from '../features/settings/sections/AppearanceSection';
import { AboutSection } from '../features/settings/sections/AboutSection';
import type { SettingsSnapshot } from '../features/settings/types';
import { PageShell, PageSection } from '../components/ui';
import { Skeleton } from '../components/ui/Skeleton';
import { usePublishPageContext } from '../hooks/usePublishPageContext';

// ── Lazy section imports — bodies live in plan-owned files ─────────────
const PoliciesSection = React.lazy(() =>
  import('../features/settings/sections/PoliciesSection').then(m => ({
    default: m.PoliciesSection,
  })),
);
const ConnectorsSection = React.lazy(() =>
  import('../features/settings/sections/ConnectorsSection').then(m => ({
    default: m.ConnectorsSection,
  })),
);
const ConflictsSection = React.lazy(() =>
  import('../features/settings/sections/ConflictsSection').then(m => ({
    default: m.ConflictsSection,
  })),
);
const AgentsSection = React.lazy(() =>
  import('../features/settings/sections/AgentsSection').then(m => ({
    default: m.AgentsSection,
  })),
);
const LibrarySection = React.lazy(() =>
  import('../features/settings/sections/LibrarySection').then(m => ({
    default: m.LibrarySection,
  })),
);
const RetrievalConfigSection = React.lazy(() =>
  import('../features/settings/sections/RetrievalConfigSection').then(m => ({
    default: m.RetrievalConfigSection,
  })),
);
const SharingSection = React.lazy(() =>
  import('../features/settings/sections/SharingSection').then(m => ({
    default: m.SharingSection,
  })),
);
const SearchModeSection = React.lazy(() =>
  import('../features/settings/sections/SearchModeSection').then(m => ({
    default: m.SearchModeSection,
  })),
);
// Phase 9 Plan 09-04 — Notifications section (NOTIF-03). Additive lazy
// import alongside the other downstream-plan sections; SettingsPage.tsx
// existed in Phase 8 with explicit extension points for this exact case.
const NotificationsSection = React.lazy(() =>
  import('../features/settings/sections/NotificationsSection').then(m => ({
    default: m.NotificationsSection,
  })),
);
// B-SET-01 — Profile / Account section.
const ProfileSection = React.lazy(() =>
  import('../features/settings/sections/ProfileSection').then(m => ({
    default: m.ProfileSection,
  })),
);
const AiModelsSection = React.lazy(() =>
  import('../features/settings/sections/AiModelsSection').then(m => ({
    default: m.AiModelsSection,
  })),
);
const SkillsSection = React.lazy(() =>
  import('../features/settings/sections/SkillsSection').then(m => ({
    default: m.SkillsSection,
  })),
);
const GetStartedSection = React.lazy(() =>
  import('../features/settings/sections/GetStartedSection').then(m => ({
    default: m.GetStartedSection,
  })),
);
// Chat dictation — per-user voice input preferences + provider status.
const VoiceInputSection = React.lazy(() =>
  import('../features/settings/sections/VoiceInputSection').then(m => ({
    default: m.VoiceInputSection,
  })),
);
const AuditLogSection = React.lazy(() =>
  import('../features/settings/sections/AuditLogSection').then(m => ({
    default: m.AuditLogSection,
  })),
);

// ── Section registry ───────────────────────────────────────────────────
// SectionId is intentionally `string` (not a Literal) so downstream plans
// can add ids additively without ever touching this file.
type SectionId = string;

interface SectionRenderCtx {
  settings: SettingsSnapshot;
  update: (
    next: SettingsSnapshot | ((prev: SettingsSnapshot) => SettingsSnapshot),
  ) => void;
  /** Programmatic nav between sections. Used for cross-section links
   *  (e.g. Providers ↔ Agents, Notifications → Connectors verify flow). */
  navigateToSection: (id: SectionId) => void;
}

interface Section {
  id: SectionId;
  label: string;
  icon: typeof Cpu;
  render: (ctx: SectionRenderCtx) => React.ReactNode;
}

// Menu items rendered alphabetically by label. Add new sections in
// alphabetical position so the nav stays sorted without a separate
// sort step at render time.
const SECTIONS: Section[] = [
  {
    id: 'about',
    label: 'About',
    icon: Info,
    render: () => <AboutSection />,
  },
  {
    id: 'ai-models',
    label: 'AI Models',
    icon: Sparkles,
    render: () => <AiModelsSection />,
  },
  {
    id: 'skills',
    label: 'AI Skills',
    icon: Wrench,
    render: () => <SkillsSection />,
  },
  {
    id: 'appearance',
    label: 'Appearance',
    icon: Palette,
    render: ctx => <AppearanceSection {...ctx} />,
  },
  {
    id: 'audit-log',
    label: 'Audit log',
    icon: ScrollText,
    render: () => <AuditLogSection />,
  },
  {
    id: 'conflicts',
    label: 'Conflicts',
    icon: AlertOctagon,
    render: () => <ConflictsSection />,
  },
  {
    id: 'connectors',
    label: 'Connectors',
    icon: Cable,
    render: () => <ConnectorsSection />,
  },
  {
    id: 'library',
    label: 'Content Profiles',
    icon: BookOpen,
    render: () => <LibrarySection />,
  },
  {
    id: 'get-started',
    label: 'Get started',
    icon: Sparkles,
    render: ctx => <GetStartedSection {...ctx} />,
  },
  {
    id: 'agents',
    label: 'Agent',
    icon: Bot,
    render: ctx => <AgentsSection {...ctx} />,
  },
  {
    id: 'notifications',
    label: 'Notifications',
    icon: Bell,
    render: () => <NotificationsSection />,
  },
  {
    id: 'policies',
    label: 'Policies',
    icon: ShieldCheck,
    render: () => <PoliciesSection />,
  },
  {
    id: 'profile',
    label: 'Profile',
    icon: UserCircle,
    render: () => <ProfileSection />,
  },
  {
    id: 'retrieval',
    label: 'Search',
    icon: Search,
    render: ctx => (
      <div className="flex flex-col gap-5">
        <SearchModeSection {...ctx} />
        <RetrievalConfigSection embedded />
      </div>
    ),
  },
  {
    id: 'sharing',
    label: 'Sharing',
    icon: Share2,
    render: () => <SharingSection />,
  },
  {
    id: 'voice-input',
    label: 'Voice input',
    icon: Mic,
    render: ctx => <VoiceInputSection navigateToSection={ctx.navigateToSection} />,
  },
];

function SectionFallback() {
  return (
    <div className="flex flex-col gap-4">
      <Skeleton className="h-6 w-40" />
      <Skeleton className="h-32 w-full" />
    </div>
  );
}

function sectionFromHash(hash: string): SectionId | null {
  // Support deep-links like `#audit-log?action=policy.deny&resource_id=...`
  const raw = hash.replace(/^#/, '').trim();
  const id = (raw.split('?')[0] || '').trim();
  if (!id) return null;
  return SECTIONS.some(s => s.id === id) ? id : null;
}

export function SettingsPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const hashSection = sectionFromHash(location.hash);
  const [active, setActive] = useState<SectionId>(hashSection ?? 'agents');

  // Which section is open — never its contents. Settings holds API keys,
  // connector credentials and model config, and page context is forwarded
  // to the backend with every turn.
  usePublishPageContext({
    pageKind: 'settings',
    metadata: { section: active },
  });
  const [settings, update] = useSettings();

  useEffect(() => {
    const fromHash = sectionFromHash(location.hash);
    if (fromHash) setActive(fromHash);
  }, [location.hash]);

  const navigateToSection = useCallback(
    (id: SectionId) => {
      setActive(id);
      navigate({ pathname: '/settings', hash: id }, { replace: true });
    },
    [navigate],
  );

  return (
    /* PageShell + PageSection so Settings aligns with every other
       editorial page (same gutter, same max-width cap). Below md the
       section nav becomes a horizontal scroll strip above the body;
       md+ uses the side-by-side column layout. */
    <PageShell>
      <PageSection innerClassName="flex flex-col gap-4 md:flex-row md:gap-8">
      {/* Section nav */}
      <aside className="w-full md:w-56 md:shrink-0">
        <header className="mb-3 flex items-center gap-2 md:mb-4">
          <SettingsIcon
            size={16}
            className="text-[var(--text-muted)]"
            strokeWidth={1.75}
          />
          <h1 className="text-sm font-semibold text-[var(--text)]">Settings</h1>
        </header>
        {/* Mobile: horizontal scroll strip — buttons inline, no wrap, the
            row scrolls under the user's thumb if the labels don't fit.
            Desktop: vertical flex column as before. Scrollbar is hidden
            so the strip reads as a Quiet Premium tab row. */}
        <nav
          className="
            -mx-4 flex flex-row gap-1 overflow-x-auto px-4
            [-webkit-overflow-scrolling:touch] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden
            md:mx-0 md:flex-col md:gap-0.5 md:overflow-visible md:px-0
          "
        >
          {SECTIONS.map(s => {
            const Icon = s.icon;
            const isActive = s.id === active;
            return (
              <button
                key={s.id}
                type="button"
                onClick={() => navigateToSection(s.id)}
                aria-current={isActive ? 'page' : undefined}
                className={`
                  inline-flex shrink-0 items-center gap-2 whitespace-nowrap rounded-[var(--radius-input)]
                  px-3 py-2 text-left text-sm transition-colors duration-fast
                  md:px-2 md:py-1.5
                  ${
                    isActive
                      ? 'bg-[var(--nav-active-bg)] text-[var(--nav-active-fg)]'
                      : 'text-[var(--text-muted)] hover:bg-[var(--panel-2)] hover:text-[var(--text)]'
                  }
                  focus:outline-none focus:ring-2 focus:ring-[var(--focus-ring-color)]
                `}
              >
                <Icon size={14} strokeWidth={1.75} />
                {s.label}
              </button>
            );
          })}
        </nav>
      </aside>

      {/* Section content */}
      <div className="min-w-0 flex-1">
        <Suspense fallback={<SectionFallback />}>
          {SECTIONS.find(s => s.id === active)?.render({
            settings,
            update,
            navigateToSection,
          })}
        </Suspense>
      </div>
      </PageSection>
    </PageShell>
  );
}
