/**
 * Phase 8 Plan 08-01 — extensible Settings nav scaffold.
 *
 * The const SECTIONS registry below is the SHARED REGISTRY across Phase 8.
 * 08-01 owns SettingsPage.tsx EXCLUSIVELY for the phase and pre-registers
 * ALL 11 sections (3 existing eager + 1 Policies eager + 7 lazy placeholders
 * filled by Plans 08-02..08-05). Downstream plans create / fill their
 * section file at the pre-agreed filepath — they DO NOT edit this file.
 *
 * Why React.lazy() for the downstream sections? Same-wave parallelism per
 * the planner's wave-assignment rule: no two same-wave plans modify the
 * same file. 08-01 lands the registry up-front so 08-02..08-05 can land
 * concurrently without touching SettingsPage.tsx.
 */
import React, { Suspense, useCallback, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  AlertOctagon,
  Bell,
  BookOpen,
  Bot,
  Cable,
  ChevronDown,
  Cpu,
  Info,
  Mic,
  Palette,
  ScrollText,
  Search,
  Settings as SettingsIcon,
  Share2,
  ShieldCheck,
  Sparkles,
  UserCircle,
  Wrench,
} from 'lucide-react';

import { useSettings } from '../features/settings/store';
import { AppearanceSection } from '../features/settings/sections/AppearanceSection';
import { AboutSection } from '../features/settings/sections/AboutSection';
import type { SettingsSnapshot } from '../features/settings/types';
import { PageShell, PageSection } from '../components/ui';
import { Skeleton } from '../components/ui/Skeleton';
import { usePublishPageContext } from '../hooks/usePublishPageContext';

// ── Lazy section imports — bodies live in plan-owned files ─────────────
const PoliciesSection = React.lazy(() =>
  import('../features/settings/sections/PoliciesSection').then(m => ({
    default: m.PoliciesSection,
  })),
);
const ConnectorsSection = React.lazy(() =>
  import('../features/settings/sections/ConnectorsSection').then(m => ({
    default: m.ConnectorsSection,
  })),
);
const ConflictsSection = React.lazy(() =>
  import('../features/settings/sections/ConflictsSection').then(m => ({
    default: m.ConflictsSection,
  })),
);
const AgentsSection = React.lazy(() =>
  import('../features/settings/sections/AgentsSection').then(m => ({
    default: m.AgentsSection,
  })),
);
const LibrarySection = React.lazy(() =>
  import('../features/settings/sections/LibrarySection').then(m => ({
    default: m.LibrarySection,
  })),
);
const RetrievalConfigSection = React.lazy(() =>
  import('../features/settings/sections/RetrievalConfigSection').then(m => ({
    default: m.RetrievalConfigSection,
  })),
);
const SharingSection = React.lazy(() =>
  import('../features/settings/sections/SharingSection').then(m => ({
    default: m.SharingSection,
  })),
);
const SearchModeSection = React.lazy(() =>
  import('../features/settings/sections/SearchModeSection').then(m => ({
    default: m.SearchModeSection,
  })),
);
// Phase 9 Plan 09-04 — Notifications section (NOTIF-03). Additive lazy
// import alongside the other downstream-plan sections; SettingsPage.tsx
// existed in Phase 8 with explicit extension points for this exact case.
const NotificationsSection = React.lazy(() =>
  import('../features/settings/sections/NotificationsSection').then(m => ({
    default: m.NotificationsSection,
  })),
);
// B-SET-01 — Profile / Account section.
const ProfileSection = React.lazy(() =>
  import('../features/settings/sections/ProfileSection').then(m => ({
    default: m.ProfileSection,
  })),
);
const AiModelsSection = React.lazy(() =>
  import('../features/settings/sections/AiModelsSection').then(m => ({
    default: m.AiModelsSection,
  })),
);
const SkillsSection = React.lazy(() =>
  import('../features/settings/sections/SkillsSection').then(m => ({
    default: m.SkillsSection,
  })),
);
const GetStartedSection = React.lazy(() =>
  import('../features/settings/sections/GetStartedSection').then(m => ({
    default: m.GetStartedSection,
  })),
);
// Chat dictation — per-user voice input preferences + provider status.
const VoiceInputSection = React.lazy(() =>
  import('../features/settings/sections/VoiceInputSection').then(m => ({
    default: m.VoiceInputSection,
  })),
);
const AuditLogSection = React.lazy(() =>
  import('../features/settings/sections/AuditLogSection').then(m => ({
    default: m.AuditLogSection,
  })),
);

// ── Section registry ───────────────────────────────────────────────────
// SectionId is intentionally `string` (not a Literal) so downstream plans
// can add ids additively without ever touching this file.
type SectionId = string;

interface SectionRenderCtx {
  settings: SettingsSnapshot;
  update: (
    next: SettingsSnapshot | ((prev: SettingsSnapshot) => SettingsSnapshot),
  ) => void;
  /** Programmatic nav between sections. Used for cross-section links
   *  (e.g. Providers ↔ Agents, Notifications → Connectors verify flow). */
  navigateToSection: (id: SectionId) => void;
}

interface Section {
  id: SectionId;
  label: string;
  icon: typeof Cpu;
  render: (ctx: SectionRenderCtx) => React.ReactNode;
}

// Menu items rendered alphabetically by label. Add new sections in
// alphabetical position so the nav stays sorted without a separate
// sort step at render time.
const SECTIONS: Section[] = [
  {
    id: 'about',
    label: 'About',
    icon: Info,
    render: () => <AboutSection />,
  },
  {
    id: 'ai-models',
    label: 'AI Models',
    icon: Sparkles,
    render: () => <AiModelsSection />,
  },
  {
    id: 'skills',
    label: 'AI Skills',
    icon: Wrench,
    render: () => <SkillsSection />,
  },
  {
    id: 'appearance',
    label: 'Appearance',
    icon: Palette,
    render: ctx => <AppearanceSection {...ctx} />,
  },
  {
    id: 'audit-log',
    label: 'Audit log',
    icon: ScrollText,
    render: () => <AuditLogSection />,
  },
  {
    id: 'conflicts',
    label: 'Conflicts',
    icon: AlertOctagon,
    render: () => <ConflictsSection />,
  },
  {
    id: 'connectors',
    label: 'Connectors',
    icon: Cable,
    render: () => <ConnectorsSection />,
  },
  {
    id: 'library',
    label: 'Operational Models',
    icon: BookOpen,
    render: () => <LibrarySection />,
  },
  {
    id: 'get-started',
    label: 'Get started',
    icon: Sparkles,
    render: ctx => <GetStartedSection {...ctx} />,
  },
  {
    id: 'agents',
    label: 'Agent',
    icon: Bot,
    render: ctx => <AgentsSection {...ctx} />,
  },
  {
    id: 'notifications',
    label: 'Notifications',
    icon: Bell,
    render: () => <NotificationsSection />,
  },
  {
    id: 'policies',
    label: 'Policies',
    icon: ShieldCheck,
    render: () => <PoliciesSection />,
  },
  {
    id: 'profile',
    label: 'Profile',
    icon: UserCircle,
    render: () => <ProfileSection />,
  },
  {
    id: 'retrieval',
    label: 'Search',
    icon: Search,
    render: ctx => (
      <div className="flex flex-col gap-5">
        <SearchModeSection {...ctx} />
        <RetrievalConfigSection embedded />
      </div>
    ),
  },
  {
    id: 'sharing',
    label: 'Sharing',
    icon: Share2,
    render: () => <SharingSection />,
  },
  {
    id: 'voice-input',
    label: 'Voice input',
    icon: Mic,
    render: ctx => <VoiceInputSection navigateToSection={ctx.navigateToSection} />,
  },
];

function SectionFallback() {
  return (
    <div className="flex flex-col gap-4">
      <Skeleton className="h-6 w-40" />
      <Skeleton className="h-32 w-full" />
    </div>
  );
}

function sectionFromHash(hash: string): SectionId | null {
  // Support deep-links like `#audit-log?action=policy.deny&resource_id=...`
  const raw = hash.replace(/^#/, '').trim();
  const id = (raw.split('?')[0] || '').trim();
  if (!id) return null;
  return SECTIONS.some(s => s.id === id) ? id : null;
}

export function SettingsPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const hashSection = sectionFromHash(location.hash);
  const [activeFallback, setActiveFallback] = useState<SectionId>('agents');
  const active = hashSection ?? activeFallback;
  const [compactMenuOpen, setCompactMenuOpen] = useState(false);

  // Which section is open — never its contents. Settings holds API keys,
  // connector credentials and model config, and page context is forwarded
  // to the backend with every turn.
  usePublishPageContext({
    pageKind: 'settings',
    metadata: { section: active },
  });
  const [settings, update] = useSettings();

  const navigateToSection = useCallback(
    (id: SectionId) => {
      setActiveFallback(id);
      setCompactMenuOpen(false);
      navigate({ pathname: '/settings', hash: id }, { replace: true });
    },
    [navigate],
  );

  return (
    /* The settings pane can be narrow even on a desktop viewport when the
      assistant is open, so its menu layout is selected by container width. */
    <PageShell>
      <div className="settings-layout-container">
        <PageSection innerClassName="settings-layout">
          {/* Section nav */}
          <aside className="settings-sidebar">
            <header className="mb-4 flex items-center gap-2">
              <SettingsIcon
                size={16}
                className="text-[var(--text-muted)]"
                strokeWidth={1.75}
              />
              <h1 className="text-sm font-semibold text-[var(--text)]">Settings</h1>
            </header>
            <nav className="flex flex-col gap-0.5">
              {SECTIONS.map(s => {
                const Icon = s.icon;
                const isActive = s.id === active;
                return (
                  <button
                    key={s.id}
                    type="button"
                    onClick={() => navigateToSection(s.id)}
                    aria-current={isActive ? 'page' : undefined}
                    className={`
                      inline-flex shrink-0 items-center gap-2 whitespace-nowrap rounded-[var(--radius-input)]
                      px-2 py-1.5 text-left text-sm transition-colors duration-fast
                      ${
                        isActive
                          ? 'bg-[var(--nav-active-bg)] text-[var(--nav-active-fg)]'
                          : 'text-[var(--text-muted)] hover:bg-[var(--panel-2)] hover:text-[var(--text)]'
                      }
                      focus:outline-none focus:ring-2 focus:ring-[var(--focus-ring-color)]
                    `}
                  >
                    <Icon size={14} strokeWidth={1.75} />
                    {s.label}
                  </button>
                );
              })}
            </nav>
          </aside>

          <div className="settings-compact-menu">
            <button
              type="button"
              aria-label={`Settings menu. Current section: ${SECTIONS.find(section => section.id === active)?.label}`}
              aria-expanded={compactMenuOpen}
              aria-controls="settings-compact-nav"
              title={SECTIONS.find(section => section.id === active)?.label}
              onClick={() => setCompactMenuOpen(open => !open)}
              className="inline-flex min-h-10 items-center gap-2 self-start rounded-[var(--radius-input)] border border-[var(--panel-border)] bg-[var(--panel)] px-3 py-2 text-sm text-[var(--text)] hover:bg-[var(--panel-2)] focus:outline-none focus:ring-2 focus:ring-[var(--focus-ring-color)]"
            >
              <SettingsIcon
                size={16}
                className="text-[var(--text-muted)]"
                strokeWidth={1.75}
              />
              <span className="settings-compact-label font-medium">
                {SECTIONS.find(section => section.id === active)?.label}
              </span>
              <ChevronDown
                size={14}
                className={`settings-compact-chevron text-[var(--text-muted)] transition-transform ${compactMenuOpen ? 'rotate-180' : ''}`}
              />
            </button>
            {compactMenuOpen && (
              <nav
                id="settings-compact-nav"
                aria-label="Settings sections"
                className="settings-compact-nav"
              >
                {SECTIONS.map(section => {
                  const Icon = section.icon;
                  const isActive = section.id === active;
                  return (
                    <button
                      key={section.id}
                      type="button"
                      onClick={() => navigateToSection(section.id)}
                      aria-current={isActive ? 'page' : undefined}
                      className={`inline-flex w-full items-center gap-2 rounded-[var(--radius-input)] px-3 py-2 text-left text-sm ${isActive ? 'bg-[var(--nav-active-bg)] text-[var(--nav-active-fg)]' : 'text-[var(--text-muted)] hover:bg-[var(--panel-2)] hover:text-[var(--text)]'}`}
                    >
                      <Icon size={14} strokeWidth={1.75} />
                      {section.label}
                    </button>
                  );
                })}
              </nav>
            )}
          </div>

          {/* Section content */}
          <div className="min-w-0 flex-1">
            <Suspense fallback={<SectionFallback />}>
              {SECTIONS.find(s => s.id === active)?.render({
                settings,
                update,
                navigateToSection,
              })}
            </Suspense>
          </div>
        </PageSection>
      </div>
    </PageShell>
  );
}
