"""Console entry point shipped in the integral-core wheel.

``integral init`` writes a distro directory: ``.env``, ``README.md``, and one
App package under ``integral-apps/<slug>/``. The directory name matches
``package.slug`` (I-BUNDLE-04).
"""

from __future__ import annotations

import argparse
import base64
import re
import secrets
import sys
from importlib.metadata import PackageNotFoundError, requires, version
from pathlib import Path

_SLUG_RE = re.compile(r"^[a-z][a-z0-9-]{0,62}$")


def _title_from_slug(slug: str) -> str:
    return " ".join(part.capitalize() for part in slug.split("-") if part)


def _manifest(slug: str, name: str) -> str:
    return f"""integral_operational_model_version: 3
scope: app

package:
  name: {name}
  slug: {slug}
  class: community_app
  version: 0.1.0
  trust_tier: trusted
  publisher: Local
  description: Starter App generated by integral init.

app:
  description: One track so the App can be installed and opened.
  defaults:
    provision_prescribed_tracks: true
    default_track: items
    default_view: items_table
  tracks:
  - key: items
    name: Items
    provision_on_create: true
    entry_types:
    - key: item
      name: Item
      fields:
      - key: summary
        name: Summary
        type: text
        required: true
    views:
    - key: items_table
      name: Items
      view_type: table
      entry_type_keys: [item]
      is_default: true
"""


def _package_pins() -> tuple[str, str]:
    """Versions to print in the generated README. Fallbacks match this tree."""
    try:
        core = version("integral-core")
    except PackageNotFoundError:
        core = "0.1.1rc5"
    jvagent = "jvagent==0.1.8rc15"
    try:
        for req in requires("integral-core") or []:
            pin = req.split(";", 1)[0].strip()
            if pin.startswith("jvagent"):
                jvagent = pin
                break
    except PackageNotFoundError:
        pass
    return core, jvagent


def _readme(slug: str, name: str, core_version: str, jvagent_pin: str) -> str:
    return f"""# {name}

Generated by `integral init`. Apps live in `integral-apps/`. Each directory
name equals `package.slug`. This starter is `{slug}`.

`tools/`, `skills/`, and `views/` are optional. A manifest-only App is enough
for Core's table, board, feed, calendar, and gallery.

## Start

Use the same Python environment that provides the `integral` command.
Postgres must already be running. This file's `.env` defaults match the
Compose database published on host port 5433.

`INTEGRAL_CREDENTIAL_ENC_KEY` is filled in so Settings → AI Models can save
a key. `OPENAI_API_KEY`, `ANTHROPIC_API_KEY`, and `OPENROUTER_API_KEY` are
the platform keys used when no one has saved a key in Settings
(`INTEGRAL_AGENT_KEY_MODE=hybrid`). Start the process from this directory
so that file is loaded.

```bash
set -a
. ./.env
set +a
python -m app.main
```

The API listens on port 4000. Set `JVSPATIAL_PORT` in `.env` when that port
is taken. Start from this directory so `.env` is loaded.

In a second terminal, from the same Python environment:

```bash
integral web
```

That serves the workspace at http://127.0.0.1:9006 and proxies `/api` and
`/ws` to the API. `integral web --api http://127.0.0.1:4010` when the API
is on another port.

## Install the package

`integral-core` pre-releases are on TestPyPI. Download only that wheel and
the matching `jvagent` wheel, then install them with PyPI as the only index.
A general TestPyPI extra index makes pip select a broken `fastapi` sdist.

```bash
python3.12 -m venv .venv
.venv/bin/pip install -U pip
.venv/bin/pip download \\
  --index-url https://test.pypi.org/simple \\
  --no-deps \\
  --dest ./wheels \\
  'integral-core=={core_version}' '{jvagent_pin}'
.venv/bin/pip install \\
  --index-url https://pypi.org/simple \\
  ./wheels/integral_core-*.whl ./wheels/jvagent-*.whl
```
"""


def _credential_key() -> str:
    """32-byte key, base64, the form openssl rand -base64 32 produces."""
    return base64.b64encode(secrets.token_bytes(32)).decode("ascii")


def _env_file(apps_dir: Path, secret: str) -> str:
    return f"""# Generated by integral init. Do not commit.
JVSPATIAL_JWT_SECRET_KEY={secret}
JVSPATIAL_DB_TYPE=postgres
POSTGRES_USER=integral
POSTGRES_PASSWORD=integral
POSTGRES_HOST=localhost
POSTGRES_PORT=5433
POSTGRES_DB=integral
INTEGRAL_PACKAGE_PATHS={apps_dir}
INTEGRAL_CORE_ONLY=0
DEBUG=true
# JVSPATIAL_PORT=4010

# Required for Settings → AI Models to store an API key.
INTEGRAL_CREDENTIAL_ENC_KEY={_credential_key()}
# hybrid: owner key from Settings when set, otherwise the platform keys below.
INTEGRAL_AGENT_KEY_MODE=hybrid
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
OPENROUTER_API_KEY=
"""


def _gitignore() -> str:
    return """.env
.venv/
wheels/
"""


def init_distro(
    dest: Path,
    *,
    slug: str,
    name: str | None = None,
    force: bool = False,
) -> Path:
    """Write a distro rooted at ``dest``. Returns ``dest``."""
    if not _SLUG_RE.match(slug) or slug.endswith("-"):
        raise ValueError(
            "slug must be lowercase letters, digits, and hyphens, "
            "and must not start or end with a hyphen"
        )
    display = (name or "").strip() or _title_from_slug(slug)
    core_version, jvagent_pin = _package_pins()
    dest = dest.expanduser().resolve()
    apps = dest / "integral-apps"
    bundle = apps / slug
    files = {
        dest / "README.md": _readme(slug, display, core_version, jvagent_pin),
        dest / ".gitignore": _gitignore(),
        dest / ".env": _env_file(apps, secrets.token_hex(32)),
        bundle / "operational-model.yaml": _manifest(slug, display),
    }
    occupied = [path for path in files if path.exists()]
    if occupied and not force:
        listed = ", ".join(str(path) for path in occupied)
        raise FileExistsError(f"refusing to overwrite {listed} (pass --force)")

    for folder in (bundle / "tools", bundle / "skills", bundle / "views"):
        folder.mkdir(parents=True, exist_ok=True)
        keep = folder / ".gitkeep"
        if not keep.exists():
            keep.write_text("", encoding="utf-8")
    for path, body in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
    return dest


def main(argv: list[str] | None = None) -> int:
    """Run the ``integral`` command-line interface."""
    parser = argparse.ArgumentParser(prog="integral")
    sub = parser.add_subparsers(dest="cmd", required=True)
    init = sub.add_parser(
        "init", help="Write an App distro (.env, README, integral-apps/)"
    )
    init.add_argument(
        "dest",
        nargs="?",
        default=".",
        type=Path,
        help="Directory to create (default: current directory)",
    )
    init.add_argument(
        "--slug", default="starter", help="App directory and package.slug"
    )
    init.add_argument(
        "--name", default="", help="Display name (default: derived from slug)"
    )
    init.add_argument("--force", action="store_true", help="Overwrite generated files")
    web = sub.add_parser("web", help="Serve the built React workspace")
    web.add_argument("--host", default="127.0.0.1", help="Bind address")
    web.add_argument("--port", type=int, default=9006, help="Listen port")
    web.add_argument(
        "--api",
        default="http://127.0.0.1:4000",
        help="API origin to proxy /api and /ws to",
    )
    args = parser.parse_args(argv)
    if args.cmd == "web":
        from app.web.server import serve_web

        try:
            serve_web(host=args.host, port=args.port, api_base=args.api)
        except FileNotFoundError as exc:
            print(f"integral web: {exc}", file=sys.stderr)
            return 1
        return 0
    if args.cmd != "init":
        return 2
    try:
        dest = init_distro(args.dest, slug=args.slug, name=args.name, force=args.force)
    except (ValueError, FileExistsError) as exc:
        print(f"integral init: {exc}", file=sys.stderr)
        return 1
    print(f"Wrote distro at {dest}")
    print(f"App package: {dest / 'integral-apps' / args.slug}")
    print("Start the API from that directory: python -m app.main")
    print("Then, in another terminal: integral web")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
