import type { LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  Archive,
  ArrowRight,
  Award,
  BarChart3,
  Bell,
  Bookmark,
  Box,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  CheckCircle,
  CheckSquare,
  ChevronRight,
  CircleDot,
  ClipboardList,
  Clock,
  Contact,
  CreditCard,
  FileSpreadsheet,
  FileText,
  Flag,
  Folder,
  FolderKanban,
  FolderOpen,
  GitBranch,
  Globe,
  Hash,
  Heart,
  HelpCircle,
  Image,
  Inbox,
  Kanban,
  Key,
  Layers,
  LayoutGrid,
  LayoutList,
  Lightbulb,
  Link2,
  ListChecks,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Package,
  Paperclip,
  Phone,
  Pin,
  Search,
  Settings,
  Shield,
  Sparkles,
  SquareStack,
  Star,
  StickyNote,
  Table,
  Tag,
  Target,
  Ticket,
  TrendingUp,
  Trophy,
  User,
  Users,
  Zap,
} from 'lucide-react';

/**
 * Maps manifest / backend ``icon`` strings (Lucide-style kebab-case or common slugs) to components.
 * Unknown ids fall back to ``FileText``.
 */
const MANIFEST_ICON_BY_ID: Record<string, LucideIcon> = {
  // Seeded CRM / PM suite (and Lucide file-name equivalents)
  building: Building,
  'building-2': Building2,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-kanban': FolderKanban,
  'check-square': CheckSquare,
  flag: Flag,
  target: Target,

  // Common manifest / UI ids
  document: FileText,
  'file-text': FileText,
  file: FileText,
  inbox: Inbox,
  mail: Mail,
  email: Mail,
  phone: Phone,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  clock: Clock,
  user: User,
  users: Users,
  contact: Contact,
  tag: Tag,
  hash: Hash,
  'layout-grid': LayoutGrid,
  table: Table,
  kanban: Kanban,
  list: LayoutList,
  layers: Layers,
  package: Package,
  box: Box,
  briefcase: Briefcase,
  'bar-chart': BarChart3,
  'bar-chart-3': BarChart3,
  'trending-up': TrendingUp,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  bell: Bell,
  shield: Shield,
  key: Key,
  'credit-card': CreditCard,
  ticket: Ticket,
  award: Award,
  trophy: Trophy,
  sparkles: Sparkles,
  zap: Zap,
  lightbulb: Lightbulb,
  globe: Globe,
  'map-pin': MapPin,
  link: Link2,
  'link-2': Link2,
  image: Image,
  paperclip: Paperclip,
  pin: Pin,
  search: Search,
  settings: Settings,
  archive: Archive,
  clipboard: ClipboardList,
  'clipboard-list': ClipboardList,
  'check-circle': CheckCircle,
  'circle-dot': CircleDot,
  'git-branch': GitBranch,
  handshake: Users,
  'square-stack': SquareStack,
  'file-spreadsheet': FileSpreadsheet,
  'arrow-right': ArrowRight,
  'chevron-right': ChevronRight,

  // Entry-type slugs (same as feed / composer conventions)
  post: StickyNote,
  task: ListChecks,
  update: Megaphone,
  issue: AlertCircle,
  idea: Lightbulb,
  question: HelpCircle,
  decision: Target,
  milestone: Trophy,
};

function normalizeIconId(raw: string): string {
  return raw.trim().toLowerCase().replace(/_/g, '-');
}

export function lucideFromOperationalModelIcon(raw?: string | null): LucideIcon {
  if (raw == null || typeof raw !== 'string') return FileText;
  const k = normalizeIconId(raw);
  if (!k) return FileText;
  return MANIFEST_ICON_BY_ID[k] ?? FileText;
}
